package database

// CreateConversationResult matches the 201 response schema in the OpenAPI spec.
type CreateConversationResult struct {
	ConversationID int64  `json:"conversationId"`
	TargetUsername string `json:"targetUsername"`
	MessageID      int64  `json:"messageId"`
	Timestamp      string `json:"timestamp"`
}

// PrivateConversationExists checks whether a private conversation already exists
// between the two specified users by looking for a PrivateChat where both
// users appear in the usChat table.
func (db *appdbimpl) PrivateConversationExists(username1 string, username2 string) (bool, error) {
	var count int
	err := db.c.QueryRow(`
		SELECT COUNT(*)
		FROM PrivateChat pc, usChat uc1, usChat uc2
		WHERE pc.chat = uc1.chat
		  AND pc.chat = uc2.chat
		  AND uc1.userOfChat = ?
		  AND uc2.userOfChat = ?
	`, username1, username2).Scan(&count)
	if err != nil {
		return false, err
	}
	return count > 0, nil
}

// CreateConversation creates a new private conversation between two users
// and sends the first message, all within a single transaction.
// This guarantees that the private conversation is always created with at least one
// message and exactly two participants.
func (db *appdbimpl) CreateConversation(sender string, target string, content string) (CreateConversationResult, error) {
	var result CreateConversationResult

	tx, err := db.c.Begin()
	if err != nil {
		return result, err
	}
	defer func() { _ = tx.Rollback() }()

	// 1. Insert a new row into Chat and retrieve the generated ID
	res, err := tx.Exec(`INSERT INTO Chat DEFAULT VALUES`)
	if err != nil {
		return result, err
	}
	chatID, err := res.LastInsertId()
	if err != nil {
		return result, err
	}

	// 2. Insert into PrivateChat (marks this chat as a private/direct conversation)
	_, err = tx.Exec(`
		INSERT INTO PrivateChat (chat) VALUES (?)
	`, chatID)
	if err != nil {
		return result, err
	}

	// 3. Insert exactly 2 participants into usChat
	//    (guarantees the private chat has exactly two members)
	_, err = tx.Exec(`
		INSERT INTO usChat (chat, userOfChat) VALUES (?, ?)
	`, chatID, sender)
	if err != nil {
		return result, err
	}
	_, err = tx.Exec(`
		INSERT INTO usChat (chat, userOfChat) VALUES (?, ?)
	`, chatID, target)
	if err != nil {
		return result, err
	}

	// 4. Insert the first message
	//    (guarantees the conversation is born with at least one message)
	msgRes, err := tx.Exec(`
		INSERT INTO Message (chat, sender, format, text, image_url, answers, forwards)
		VALUES (?, ?, 'TEXT', ?, NULL, NULL, NULL)
	`, chatID, sender, content)
	if err != nil {
		return result, err
	}
	messageID, err := msgRes.LastInsertId()
	if err != nil {
		return result, err
	}

	// 5. Retrieve the timestamp generated by SQLite
	var timestamp string
	err = tx.QueryRow(`
		SELECT instant FROM Message WHERE id = ?
	`, messageID).Scan(&timestamp)
	if err != nil {
		return result, err
	}

	// 6. Insert a 'sent' status row in messageStatus for the recipient
	_, err = tx.Exec(`
		INSERT INTO messageStatus (message, userOfMessageStatus, status)
		VALUES (?, ?, 'sent')
	`, messageID, target)
	if err != nil {
		return result, err
	}

	if err := tx.Commit(); err != nil {
		return result, err
	}

	result.ConversationID = chatID
	result.TargetUsername = target
	result.MessageID = messageID
	result.Timestamp = timestamp

	return result, nil
}
