package database

import (
	"database/sql"
)

// MessageForwardedResult matches the MessageForwarded schema in the OpenAPI spec.
type MessageForwardedResult struct {
	ID                   int64  `json:"id"`
	Checkmarks           int    `json:"checkmarks"`
	Timestamp            string `json:"timestamp"`
	Content              string `json:"content,omitempty"`
	PhotoURL             string `json:"photoUrl,omitempty"`
	TargetConversationID int64  `json:"targetConversationId"`
}

// ForwardMessage copies the content of the original message into the target conversation,
// setting the "forwards" field to link back to the original.
// A transaction is required because Message and messageStatus must be written atomically.
func (db *appdbimpl) ForwardMessage(messageID int64, targetConversationID int64, sender string) (MessageForwardedResult, error) {
	var result MessageForwardedResult

	// 1. Read the content of the original message
	var format string
	var text sql.NullString
	var imageURL sql.NullString
	err := db.c.QueryRow(`
		SELECT format, text, image_url
		FROM Message
		WHERE id = ?
	`, messageID).Scan(&format, &text, &imageURL)
	if err != nil {
		return result, err
	}

	tx, err := db.c.Begin()
	if err != nil {
		return result, err
	}
	defer func() { _ = tx.Rollback() }()

	// 2. Insert the new message into the target conversation.
	//    The "forwards" field links back to the original message.
	//    The "answers" field is NULL because a forward is not a reply.
	res, err := tx.Exec(`
		INSERT INTO Message (chat, sender, format, text, image_url, answers, forwards)
		VALUES (?, ?, ?, ?, ?, NULL, ?)
	`,
		targetConversationID,
		sender,
		format,
		nullableString(text.String),
		nullableString(imageURL.String),
		messageID,
	)
	if err != nil {
		return result, err
	}
	newMessageID, err := res.LastInsertId()
	if err != nil {
		return result, err
	}

	// 3. Retrieve the timestamp generated by SQLite
	var timestamp string
	err = tx.QueryRow(`
		SELECT instant FROM Message WHERE id = ?
	`, newMessageID).Scan(&timestamp)
	if err != nil {
		return result, err
	}

	// 4. Retrieve participants of the target conversation
	//    and create messageStatus rows for each one (excluding the sender)
	rows, err := tx.Query(`
		SELECT userOfChat FROM usChat WHERE chat = ?
	`, targetConversationID)
	if err != nil {
		return result, err
	}
	defer rows.Close()

	for rows.Next() {
		var participant string
		if err := rows.Scan(&participant); err != nil {
			return result, err
		}
		if participant == sender {
			continue
		}
		_, err = tx.Exec(`
			INSERT INTO messageStatus (message, userOfMessageStatus, status)
			VALUES (?, ?, 'sent')
		`, newMessageID, participant)
		if err != nil {
			return result, err
		}
	}
	if err := rows.Err(); err != nil {
		return result, err
	}

	if err := tx.Commit(); err != nil {
		return result, err
	}

	result.ID = newMessageID
	result.Checkmarks = 0
	result.Timestamp = timestamp
	result.TargetConversationID = targetConversationID
	if format == "TEXT" {
		result.Content = text.String
	} else {
		result.PhotoURL = imageURL.String
	}

	return result, nil
}
