package database

// MessageCreatedResult matches the 201 response schema
// for sendMessage (MessageCreated schema in the OpenAPI spec).
type MessageCreatedResult struct {
	ID         int64  `json:"id"`
	Checkmarks int    `json:"checkmarks"`
	Timestamp  string `json:"timestamp"`
	Content    string `json:"content,omitempty"`
	PhotoURL   string `json:"photoUrl,omitempty"`
}

// InsertTextMessage inserts a text message into the conversation
// and creates messageStatus rows for all participants.
// Returns the created message data.
func (db *appdbimpl) InsertTextMessage(conversationID int64, sender string, content string, replyToID *int64) (MessageCreatedResult, error) {
	return db.insertMessage(conversationID, sender, "TEXT", content, "", replyToID)
}

// InsertImageMessage inserts an image message into the conversation.
func (db *appdbimpl) InsertImageMessage(conversationID int64, sender string, imageURL string) (MessageCreatedResult, error) {
	return db.insertMessage(conversationID, sender, "IMAGE", "", imageURL, nil)
}

// insertMessage is the shared internal function used by InsertTextMessage and InsertImageMessage.
// A transaction is used because Message and messageStatus must be written atomically.
func (db *appdbimpl) insertMessage(conversationID int64, sender string, format string, text string, imageURL string, replyToID *int64) (MessageCreatedResult, error) {
	var result MessageCreatedResult

	tx, err := db.c.Begin()
	if err != nil {
		return result, err
	}
	defer func() { _ = tx.Rollback() }()

	// 1. Insert the message into the Message table
	res, err := tx.Exec(`
		INSERT INTO Message (chat, sender, format, text, image_url, answers)
		VALUES (?, ?, ?, ?, ?, ?)
	`,
		conversationID,
		sender,
		format,
		nullableString(text),
		nullableString(imageURL),
		replyToID, // already a *int64 — SQLite stores nil as NULL
	)
	if err != nil {
		return result, err
	}
	messageID, err := res.LastInsertId()
	if err != nil {
		return result, err
	}

	// 2. Retrieve the timestamp generated by SQLite (DEFAULT CURRENT_TIMESTAMP)
	var timestamp string
	err = tx.QueryRow(`
		SELECT instant FROM Message WHERE id = ?
	`, messageID).Scan(&timestamp)
	if err != nil {
		return result, err
	}

	// 3. Retrieve all participants of the conversation
	//    in order to create messageStatus rows for each one
	rows, err := tx.Query(`
		SELECT userOfChat FROM usChat WHERE chat = ?
	`, conversationID)
	if err != nil {
		return result, err
	}
	defer rows.Close()

	var participants []string
	for rows.Next() {
		var p string
		if err := rows.Scan(&p); err != nil {
			return result, err
		}
		participants = append(participants, p)
	}
	if err := rows.Err(); err != nil {
		return result, err
	}

	// 4. Insert a messageStatus row for each participant.
	//    The sender does not get a status row (they do not need to track
	//    whether they have "read" their own message), so those are skipped.
	//    For all other participants the initial status is 'sent'.
	for _, p := range participants {
		if p == sender {
			continue
		}
		_, err = tx.Exec(`
			INSERT INTO messageStatus (message, userOfMessageStatus, status)
			VALUES (?, ?, 'sent')
		`, messageID, p)
		if err != nil {
			return result, err
		}
	}

	if err := tx.Commit(); err != nil {
		return result, err
	}

	result.ID = messageID
	result.Checkmarks = 0 // just sent: no recipient has received it yet
	result.Timestamp = timestamp
	if format == "TEXT" {
		result.Content = text
	} else {
		result.PhotoURL = imageURL
	}

	return result, nil
}

// nullableString converts an empty string to nil so that SQLite stores NULL
// instead of an empty string, which would violate the CHECK constraints.
func nullableString(s string) interface{} {
	if s == "" {
		return nil
	}
	return s
}
